---
- hosts: all
  tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts['default_ipv4']['address']
    - name: Register a variable
      ansible.builtin.shell: cat /etc/motd
      register: motd_contents
    - name: Dump motd
      debug:
        var: motd_contents
