---
- hosts: all
  become: true
  tasks:
    - include_tasks: hello-tasks-debian.yml
      when: ansible_facts['os_family'] == "Debian"
    - include_tasks: hello-tasks-redhat.yml
      when: ansible_facts['os_family'] == "RedHat"
