---
- name: Hello, Ansible Playbook
  hosts: all
  become: true
  tasks:
    - name: Example from Ansible Playbook
      ansible.builtin.ping:
    - name: Show gateway
      ansible.builtin.debug:
        msg: "{{ ansible_default_ipv4.gateway }}"

    - name: Install apache debian
      ansible.builtin.apt:
        name: apache2
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install apache redhat
      ansible.builtin.yum:
        name: httpd
      when: ansible_facts['os_family'] == "RedHat"

    - name: Start apache debian
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Start apache redhat
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install mariadb
      ansible.builtin.apt:
        name: mariadb-server
    - name: Uninstall htop
      ansible.builtin.apt:
        name: htop
        state: absent
    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
    - name: Desplegar aplicacion
      ansible.builtin.unarchive:
        src: /home/tux/Downloads/2048.zip
        dest: /var/www/html/
        owner: root
        group: root

    - name: Install mariadb
      ansible.builtin.yum:
        name: mariadb-server
    - name: Uninstall htop
      ansible.builtin.yum:
        name: htop
        state: absent
    - name: Install unzip
      ansible.builtin.yum:
        name: unzip
    - name: Desplegar aplicacion
      ansible.builtin.unarchive:
        src: /home/tux/Downloads/2048.zip
        dest: /var/www/html/
        owner: root
        group: root
